### PR TITLE
feat(example): add see also

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Add a `friends` section so humans can discover other low level packages that are related but not part of this :sparkles:

cc/ @Kriesse 

screen shot 2016-11-01 at 16 00 11

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
the horizontal alignment of the two sections is really getting to me haha 😢

**Review by Kriesse — APPROVED** [review]
LGTM

**Comment by Kriesse** [comment]
Will work on layout issues in a separate branch https://github.com/yoshuawuyts/base-elements/issues/11

**Comment by yoshuawuyts** [comment]
yay!

**Pull request merged**
